
-- Autogenerated by Jack
--
-- MySQL dump for testing purposes. DO NOT USE THIS IN PRODUCTION!
--

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT,
  `commenter_id` INTEGER NOT NULL,
  `commented_on_id` INTEGER NOT NULL,
  `created_at` DATETIME NOT NULL default '1970-01-01 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `images`;
CREATE TABLE `images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` INTEGER,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255),
  `posted_at_millis` DATE,
  `user_id` INTEGER,
  `updated_at` DATETIME,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `handle` VARCHAR(255) NOT NULL,
  `created_at_millis` INTEGER,
  `num_posts` INTEGER NOT NULL,
  `some_date` DATE,
  `some_datetime` DATETIME,
  `bio` TEXT,
  `some_binary` BLOB,
  `some_float` FLOAT,
  `some_boolean` TINYINT(1),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
