
-- Autogenerated by Jack
--
-- MySQL dump for testing purposes. DO NOT USE THIS IN PRODUCTION!
--

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `content` CHAR,
  `commenter_id` INTEGER NOT NULL,
  `commented_on_id` INTEGER NOT NULL,
  `created_at` DATE NOT NULL default '1970-01-01 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `images`;
CREATE TABLE `images` (
  `user_id` INTEGER
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `title` CHAR,
  `posted_at_millis` DATE,
  `user_id` INTEGER,
  `updated_at` DATE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `handle` CHAR NOT NULL,
  `created_at_millis` INTEGER,
  `num_posts` INTEGER NOT NULL,
  `some_date` DATE,
  `some_datetime` DATE,
  `bio` CHAR,
  `some_binary` BINARY,
  `some_float` DOUBLE,
  `some_boolean` BOOLEAN
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
